/* prettier-ignore-start */

/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as LayoutAuthProfileRouteImport } from './routes/_layout/_auth/profile/route';
import { Route as LayoutAuthRouteImport } from './routes/_layout/_auth/route';
import { Route as LayoutAsideRouteImport } from './routes/_layout/aside/route';
import { Route as LayoutHomeRouteImport } from './routes/_layout/home/route';
import { Route as LayoutInvoicesInvoiceIdImport } from './routes/_layout/invoices/$invoiceId';
import { Route as LayoutInvoicesIndexImport } from './routes/_layout/invoices/index';
import { Route as LayoutInvoicesRouteImport } from './routes/_layout/invoices/route';
import { Route as LayoutRouteImport } from './routes/_layout/route';
import { Route as IndexImport } from './routes/index';
import { Route as LoginRouteImport } from './routes/login/route';
import { createFileRoute } from '@tanstack/react-router';

// Create Virtual Routes

const LayoutExpensiveIndexLazyImport = createFileRoute('/_layout/expensive/')();

// Create/Update Routes

const LoginRouteRoute = LoginRouteImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const LayoutRouteRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const LayoutInvoicesRouteRoute = LayoutInvoicesRouteImport.update({
  path: '/invoices',
  getParentRoute: () => LayoutRouteRoute,
} as any);

const LayoutHomeRouteRoute = LayoutHomeRouteImport.update({
  path: '/home',
  getParentRoute: () => LayoutRouteRoute,
} as any);

const LayoutAsideRouteRoute = LayoutAsideRouteImport.update({
  path: '/aside',
  getParentRoute: () => LayoutRouteRoute,
} as any);

const LayoutAuthRouteRoute = LayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRouteRoute,
} as any);

const LayoutExpensiveIndexLazyRoute = LayoutExpensiveIndexLazyImport.update({
  path: '/expensive/',
  getParentRoute: () => LayoutRouteRoute,
} as any).lazy(() => import('./routes/_layout/expensive/index.lazy').then((d) => d.Route));

const LayoutInvoicesIndexRoute = LayoutInvoicesIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutInvoicesRouteRoute,
} as any);

const LayoutInvoicesInvoiceIdRoute = LayoutInvoicesInvoiceIdImport.update({
  path: '/$invoiceId',
  getParentRoute: () => LayoutInvoicesRouteRoute,
} as any);

const LayoutAuthProfileRouteRoute = LayoutAuthProfileRouteImport.update({
  path: '/profile',
  getParentRoute: () => LayoutAuthRouteRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof LayoutRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/_layout/_auth': {
      id: '/_layout/_auth';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof LayoutAuthRouteImport;
      parentRoute: typeof LayoutRouteImport;
    };
    '/_layout/aside': {
      id: '/_layout/aside';
      path: '/aside';
      fullPath: '/aside';
      preLoaderRoute: typeof LayoutAsideRouteImport;
      parentRoute: typeof LayoutRouteImport;
    };
    '/_layout/home': {
      id: '/_layout/home';
      path: '/home';
      fullPath: '/home';
      preLoaderRoute: typeof LayoutHomeRouteImport;
      parentRoute: typeof LayoutRouteImport;
    };
    '/_layout/invoices': {
      id: '/_layout/invoices';
      path: '/invoices';
      fullPath: '/invoices';
      preLoaderRoute: typeof LayoutInvoicesRouteImport;
      parentRoute: typeof LayoutRouteImport;
    };
    '/_layout/_auth/profile': {
      id: '/_layout/_auth/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof LayoutAuthProfileRouteImport;
      parentRoute: typeof LayoutAuthRouteImport;
    };
    '/_layout/invoices/$invoiceId': {
      id: '/_layout/invoices/$invoiceId';
      path: '/$invoiceId';
      fullPath: '/invoices/$invoiceId';
      preLoaderRoute: typeof LayoutInvoicesInvoiceIdImport;
      parentRoute: typeof LayoutInvoicesRouteImport;
    };
    '/_layout/invoices/': {
      id: '/_layout/invoices/';
      path: '/';
      fullPath: '/invoices/';
      preLoaderRoute: typeof LayoutInvoicesIndexImport;
      parentRoute: typeof LayoutInvoicesRouteImport;
    };
    '/_layout/expensive/': {
      id: '/_layout/expensive/';
      path: '/expensive';
      fullPath: '/expensive';
      preLoaderRoute: typeof LayoutExpensiveIndexLazyImport;
      parentRoute: typeof LayoutRouteImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LayoutRouteRoute: LayoutRouteRoute.addChildren({
    LayoutAuthRouteRoute: LayoutAuthRouteRoute.addChildren({
      LayoutAuthProfileRouteRoute,
    }),
    LayoutAsideRouteRoute,
    LayoutHomeRouteRoute,
    LayoutInvoicesRouteRoute: LayoutInvoicesRouteRoute.addChildren({
      LayoutInvoicesInvoiceIdRoute,
      LayoutInvoicesIndexRoute,
    }),
    LayoutExpensiveIndexLazyRoute,
  }),
  LoginRouteRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout/route.tsx",
      "children": [
        "/_layout/_auth",
        "/_layout/aside",
        "/_layout/home",
        "/_layout/invoices",
        "/_layout/expensive/"
      ]
    },
    "/login": {
      "filePath": "login/route.tsx"
    },
    "/_layout/_auth": {
      "filePath": "_layout/_auth/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_auth/profile"
      ]
    },
    "/_layout/aside": {
      "filePath": "_layout/aside/route.tsx",
      "parent": "/_layout"
    },
    "/_layout/home": {
      "filePath": "_layout/home/route.tsx",
      "parent": "/_layout"
    },
    "/_layout/invoices": {
      "filePath": "_layout/invoices/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/invoices/$invoiceId",
        "/_layout/invoices/"
      ]
    },
    "/_layout/_auth/profile": {
      "filePath": "_layout/_auth/profile/route.tsx",
      "parent": "/_layout/_auth"
    },
    "/_layout/invoices/$invoiceId": {
      "filePath": "_layout/invoices/$invoiceId.tsx",
      "parent": "/_layout/invoices"
    },
    "/_layout/invoices/": {
      "filePath": "_layout/invoices/index.tsx",
      "parent": "/_layout/invoices"
    },
    "/_layout/expensive/": {
      "filePath": "_layout/expensive/index.lazy.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
